#!/usr/bin/env python
"""

Upload PDF to Noark 5 API for archiving.

"""

import sys
sys.path.append('lib')

import argparse
import json
import n5core.endpoint
from pyPdf import PdfFileReader

def objectOperation(json, relation):
    """
Return the URL/href for a given relation on the object represented by
the json structure.

"""
    if '_links' not in json:
        return None
    for l in json['_links']:
        if l['rel'] == relation:
            return l['href']
    return None

def pickUnlessOne(json, type):
    """
Check the array in the json structure, if there is only one elemet, return it.
If there are more than one elemet, ask the user to pick one.
"""
    print("Found %d %s entries" % (len(json), type))
    count = len(json)
    if 0 == count:
        return None
    if 1 == count:
        print(json[0]['tittel'])
        return json[0]
    else:
        n = -1
        while -1 == n:
            i = 0
            for entry in json:
                print(" %d - %s" % (i, entry['tittel']))
                i = i + 1
            n = int(raw_input("Select which %s you want: " % type))
            if n < 0 or n >= count:
                print("Invalid selection %d" % n)
                n = -1
            else:
                return json[int(n)]

def main():
    parser = argparse.ArgumentParser()
#        parser.add_argument("--reference", help="connect to demo API site",
#                            action="store_true")
    parser.add_argument("pdffile", nargs='+', help="PDF file to archive")
    args = parser.parse_args()
        
    baseurl = "http://localhost:8092/noark5v4/"
    api = n5core.endpoint.Endpoint(baseurl)
    api.verbose = True
    api.login()

    fondshref = api.findRelation('http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkiv/')
    
    (c, res) = api.json_get(fondshref)
    fondsinfo = json.loads(c)
    info = pickUnlessOne(fondsinfo, 'arkiv')

    serieshref = objectOperation(info,
                                 'http://rel.kxml.no/noark5/v4/api/arkivstruktur/arkivdel/')
    print("Arkivdel %s" % serieshref)
    (c, res) = api.json_get(serieshref)
    seriesinfo = json.loads(c)
    info = pickUnlessOne(seriesinfo, 'arkivdel')

    fileshref = objectOperation(info,
                               'http://rel.kxml.no/noark5/v4/api/arkivstruktur/mappe/')
    print("Mappe %s" % fileshref)
    (c, res) = api.json_get(fileshref)
    filessinfo = json.loads(c)
    info = pickUnlessOne(filesinfo, 'mappe')
    
    print

    for pdfname in (args.pdffile):
        print(pdfname)
        pdf = PdfFileReader(file(pdfname, "rb"))
        print(pdf.getDocumentInfo().title)
        print(pdf.getDocumentInfo().producer)
        print(pdf.getDocumentInfo().creator)
        #pdf.getDocumentInfo().creationdate ?

if __name__ == '__main__':
    main()
